### ISSUE TITLE
Add social media image

### ISSUE THREAD

**Issue by casassg** [HackCU/splash-page#1]
Add an image to show as preview with social media. It should look like this:

https://github.com/hackupc/subscribe/blob/master/src/images/hackupc-ogimage%402x.png

**Comment by jessalbarian** [comment]
I added the ogimage. I'm just waiting until we change the URL from beta to hackcu.org

**Comment by AparaV** [comment]
Fixed by @jessalbarian in commit https://github.com/HackCU/splash-page/commit/4ef1673b6acdd7c902111cdb3345883cfa38a8b9
